# Reference: https://docs.docker.com/compose/compose-file/compose-file-v2
services:
  wildfly:
    build:
      context: ./jboss
    ports:
    # HOST:CONTAINER
    # Note that the default container ports are prefixed with 1 for local ports to prevent clashes with existing jboss containers.
    - 9999:9999
    - 9990:9990
    - 8080:8080
    - 8787:8787
version: '2.1'
